
//export default  AG_GRID_LOCALE_FA;

export const AG_GRID_LOCALE_FA = {
  // Set Filter
  selectAll: '(انتخاب همه)',
  selectAllSearchResults: '(انتخاب خمه موارد یافت شده)',
  searchOoo: 'جستجو...',
  blanks: '(خالی)',
  noMatches: 'هیچ موردی',

  // Number Filter & Text Filter
  filterOoo: 'فیلتر...',
  equals: 'برابر',
  notEqual: 'نا برابر',
  empty: 'انتخاب',

  // Number Filter
  lessThan: 'کوچکتر',
  greaterThan: 'بزرگتر',
  lessThanOrEqual: 'کوچکتر مساوی',
  greaterThanOrEqual: 'بزرگتر مساوی',
  inRange: 'فی مابین',
  inRangeStart: 'از',
  inRangeEnd: 'تا',

  // Text Filter
  contains: 'شامل',
  notContains: 'شامل نباشد',
  startsWith: 'شروع با',
  endsWith: 'خاتمه با',

  // Date Filter
  dateFormatOoo: 'yyyy-mm-dd',

  // Filter Conditions
  andCondition: 'و',
  orCondition: 'یا',

  // Filter Buttons
  applyFilter: 'اعمال',
  resetFilter: 'بازنشانی',
  clearFilter: 'پاک',
  cancelFilter: 'انصراف',

  // Filter Titles
  textFilter: 'فیلتر متن',
  numberFilter: 'فیلتر عدد',
  dateFilter: 'فیلتر تاریخ',
  setFilter: 'تنظیم فیلتر',

  // Side Bar
  columns: 'ستون ها',
  filters: 'فیلتر ها',

  // columns tool panel
  pivotMode: 'مدل پیووت',
  groups: 'گروهبندی ردیف',
  rowGroupColumnsEmptyMessage: 'برای گروه بندی ستون مورد نظر را اینجا بکشید',
  values: 'مقادیر',
  valueColumnsEmptyMessage: 'Drag here to aggregate',
  pivots: 'برچسب های ستون',
  pivotColumnsEmptyMessage: 'ستون مورد نظر را برای تعیین نام ستون ها اینجا بکشید',

  // Header of the Default Group Column
  group: 'Group',

  // Other
  loadingOoo: 'در حال بارگذاری...',
  noRowsToShow: 'هیچ رکوردی برای نمایش وجود ندارد',
  enabled: 'فعال',

  // Menu
  pinColumn: 'پین کردن ستون',
  pinLeft: 'پین به چپ',
  pinRight: 'پین به راست',
  noPin: 'بدون پین',
  valueAggregation: 'بررسب مقادیر',
  autosizeThiscolumn: 'اندازه اتومات این ستون',
  autosizeAllColumns: 'اندازه اتومات تمام ستون ها',
  groupBy: 'Group by',
  ungroupBy: 'Un-Group by',
  resetColumns: 'باز نشانی ستون ها',
  expandAll: 'باز کردن همه',
  collapseAll: 'بستن همه',
  copy: 'کپی',
  ctrlC: 'Ctrl+C',
  copyWithHeaders: 'کپی به همراه نام ستون',
  paste: 'چسباندن(paste)',
  ctrlV: 'Ctrl+V',
  export: 'خروجی',
  csvExport: 'خروجی CSV',
  excelExport: 'خروجی Excel',

  // Enterprise Menu Aggregation and Status Bar
  sum: 'جمع',
  min: 'کمینه',
  max: 'بیشینه',
  none: 'هیج',
  count: 'تعداد',
  avg: 'میانگین',
  filteredRows: 'فیلتر شده',
  selectedRows: 'انتخاب شده',
  totalRows: 'کل ردیف ها',
  totalAndFilteredRows: 'ردیف ها',
  more: 'بیشتر',
  to: 'تا',
  of: 'از',
  page: 'صفحه',
  nextPage: 'صفحه بعد',
  lastPage: 'صفحه بعد',
  firstPage: 'اولین صفحه',
  previousPage: 'آخرین صفحه',

  // Pivoting
  pivotColumnGroupTotals: 'کل',

  // Enterprise Menu (Charts)
  pivotChartAndPivotMode: 'نمودار محوری و حالت محوری',
  pivotChart: 'نمودار محوری(Pivot)',
  chartRange: 'ترسیم نمودار',

  columnChart: 'ستونی',
  groupedColumn: 'گروه بندی شده',
  stackedColumn: 'انباشته',
  normalizedColumn: '100% انباشته',

  barChart: 'میله ای(Bar)',
  groupedBar: 'گروه بندی شده',
  stackedBar: 'انباشته',
  normalizedBar: '100% انباشته',

  pieChart: 'دایره ای(Pie)',
  pie: 'دایره ای(Pie)',
  doughnut: 'حلقه ای(Doughnut)',

  line: 'خطی(Line)',

  xyChart: 'X Y (پراکندگی)',
  scatter: 'پراکندگی',
  bubble: 'حبابی',

  areaChart: 'حوزه',
  area: 'حوزه',
  stackedArea: 'انباشته',
  normalizedArea: '100% انباشته',

  histogramChart: 'Histogram',

  // Charts
  pivotChartTitle: 'نمودار محوری (Pivot)',
  rangeChartTitle: 'نمودار محدوده ای',
  settings: 'تنظیمات',
  data: 'اطلاعات',
  format: 'پیکر بندی',
  categories: 'گروه ها',
  defaultCategory: '(هیچ)',
  series: 'سری ها',
  xyValues: 'X Y مقادیر',
  paired: 'حالت پین شده',
  axis: 'محور(Axis)',
  navigator: 'ناوبر',
  color: 'رنگ',
  thickness: 'ضخامت',
  xType: 'X نوع',
  automatic: 'اتومات',
  category: 'گروه بندی',
  number: 'عدد',
  time: 'زمان',
  xRotation: 'X چرخش',
  yRotation: 'Y چرخش',
  ticks: 'تیک ها',
  width: 'عرض',
  height: 'HVJTHU',
  length: 'طول',
  padding: 'لایه گذاری',
  spacing: 'فاصله',
  chart: 'نمودار',
  title: 'عنوان',
  titlePlaceholder: 'عنوان نمودار - برای ویرایش دوبار کلیک کنیدt',
  background: 'پس زمینه',
  font: 'قلم(Font)',
  top: 'بالا',
  right: 'راست',
  bottom: 'پایین',
  left: 'چپ',
  labels: 'برچسب ها',
  size: 'اندازه',
  minSize: 'حداقل اندازه',
  maxSize: 'حداکثر اندازه',
  legend: 'راهنما',
  position: 'موقعیت',
  markerSize: 'اندازه نشانگر',
  markerStroke: 'هاشور نشانگر',
  markerPadding: 'نشانگر لایه گذاری',
  itemSpacing: 'فضای ایتم ها',
  itemPaddingX: 'لایه ایتم ها X',
  itemPaddingY: 'لایه ایتم ها Y',
  layoutHorizontalSpacing: 'فضای افقی',
  layoutVerticalSpacing: 'فضای عمودی',
  strokeWidth: 'هاشور عرضی',
  offset: 'انحراف',
  offsets: 'انحراف ها',
  tooltips: 'راهنما(Tooltips)',
  callout: 'فراخوان',
  markers: 'نشانگر ها',
  shadow: 'سایه',
  blur: 'محو کردن',
  xOffset: 'X انحراف',
  yOffset: 'Y انحراف',
  lineWidth: 'خط عرضی',
  normal: 'معمولی',
  bold: 'پررنگ',
  italic: 'ایتالیک',
  boldItalic: 'پررنگ ایتالیک',
  predefined: 'از پیش تعریف شده',
  fillOpacity: 'کدری',
  strokeOpacity: 'کدری خطی',
  histogramBinCount: 'تعداد سطل',
  columnGroup: 'ستونی',
  barGroup: 'میله ای',
  pieGroup: 'دایره ای',
  lineGroup: 'خطی',
  scatterGroup: 'X Y (پراکنده)',
  areaGroup: 'حوزه',
  histogramGroup: 'Histogram',
  groupedColumnTooltip: 'گروه بندی شده',
  stackedColumnTooltip: 'انباشته',
  normalizedColumnTooltip: '100% انباشته',
  groupedBarTooltip: 'گروه بندی شده',
  stackedBarTooltip: 'انباشته',
  normalizedBarTooltip: '100% انباشته',
  pieTooltip: 'دایره ای',
  doughnutTooltip: 'حلقه ای',
  lineTooltip: 'خطی',
  groupedAreaTooltip: 'حوزه ای',
  stackedAreaTooltip: 'انباشته',
  normalizedAreaTooltip: '100% انباشته',
  scatterTooltip: 'پراکنده',
  bubbleTooltip: 'حبابی',
  histogramTooltip: 'Histogram',
  noDataToChart: 'داده معتبری برای ترسیم نمودار وجود ندارد',
  pivotChartRequiresPivotMode: 'نمودار محوری نیاز به فعال کردن حالت محوری دارد.',
  chartSettingsToolbarTooltip: 'منو',
  chartLinkToolbarTooltip: 'اتصال به جدول',
  chartUnlinkToolbarTooltip: 'قطع اتصال از جدول',
  chartDownloadToolbarTooltip: 'بارگیری نمودار',

  // ARIA
  ariaHidden: 'مخفی',
  ariaVisible: 'قابل نمایش',
  ariaChecked: 'انتخاب شده',
  ariaUnchecked: 'انتخاب نشده',
  ariaIndeterminate:'نا مشخص',
  ariaColumnSelectAll: 'تغییر حالت به انتخاب همه ستون ها',
  ariaInputEditor: 'Input Editor',
  ariaDateFilterInput: 'Date Filter Input',
  ariaFilterInput: 'Filter Input',
  ariaFilterColumnsInput: 'Filter Columns Input',
  ariaFilterValue: 'Filter Value',
  ariaFilterFromValue: 'Filter from value',
  ariaFilterToValue: 'Filter to value',
  ariaFilteringOperator: 'Filtering Operator',
  ariaColumnToggleVisibility: 'column toggle visibility',
  ariaColumnGroupToggleVisibility: 'column group toggle visibility',
  ariaRowSelect: 'Press SPACE to select this row',
  ariaRowDeselect: 'Press SPACE to deselect this row',
  ariaRowToggleSelection: 'Press Space to toggle row selection',
  ariaRowSelectAll: 'Press Space to toggle all rows selection',
  ariaSearch: 'Search',
  ariaSearchFilterValues: 'Search filter values'
};