

export const CLEAR_DATASET = "CLEAR_DATASET"
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const DO_FETCH_DATA = "DO_FETCH_DATA"



