/* CHATS */
export const GET_MENUS = "GET_MENUS"
export const GET_MENUS_SUCCESS = "GET_MENUS_SUCCESS"
export const GET_MENUS_FAILURE = "GET_MENUS_FAILURE"

export const ADD_MENU = "ADD_MENU"
export const ADD_MENU_SUCCESS = "ADD_MENU_SUCCESS"
export const ADD_MENU_FAILURE = "ADD_MENU_FAILURE"

export const DELETE_MENU = "DELETE_MENU"
export const DELETE_MENU_SUCCESS = "DELETE_MENU_SUCCESS"
export const DELETE_MENU_FAILURE = "DELETE_MENU_FAILURE"


